# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            EECE 210
tagline:          'Principles of Software Construction'
description:      'Principles of Software Construction'
url:              'http://gsathish.github.io/eece210'

author:
  name:           'Sathish Gopalakrishnan'
  url:            http://www.ece.ubc.ca/~sathish

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gsathish/eece210
