# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Principles of Software Construction
tagline:          'EECE 210'
description:      'EECE 210 // UBC'
url:              http://gsathish.github.io/eece210

author:
  name:           'Sathish Gopalakrishnan'
  url:            http://www.ece.ubc.ca/~sathish

paginate:         5

# Custom vars
version:          2014

github:
  repo:           https://github.com/gsathish/eece210
